_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1

min_epochs: 1
max_epochs: 2000

weights_summary: null
progress_bar_refresh_rate: 10

resume_from_checkpoint: "E:/YandexDisk/Work/dnamvae/models/logs/runs/2021-05-26/02-14-39/checkpoints/epoch=643.ckpt"
# resume_from_checkpoint: null
