_target_: src.models.extractor_mlp_model.ExtractorFCMLPModel

extractor_path: "E:/YandexDisk/Work/dnamvae/models/logs/runs/2021-06-07/18-31-48/checkpoints/epoch=19.ckpt"
task: "regression"
n_output: 1
topology: [400, 200, 100]
dropout: 0.0
num_unfreeze_epochs: 10
loss_type: "MSE"
extractor_type: "FCAEModel"
lr: 0.001
weight_decay: 0.0005
