_target_: src.models.extractor_mlp_model.ExtractorFCMLPModel

extractor_path: "E:/YandexDisk/Work/dnamvae/models/fcvae_model_v2/logs/runs/2021-06-09/22-12-47/checkpoints/epoch=88_fold_4.ckpt"
task: "regression"
n_output: 1
topology: [128, 128]
dropout: 0.0
num_unfreeze_epochs: 10
loss_type: "MSE"
extractor_type: "FCVAEModelV2"
lr: 0.0001
weight_decay: 0.00005
