_target_: src.models.extractor_mlp_model.ExtractorFCMLPModel

extractor_path: "E:/YandexDisk/Work/dnamvae/models/fcae_model/logs/runs/2021-06-10/18-04-21/checkpoints/epoch=08_fold_1.ckpt"
task: "regression"
n_output: 1
topology: [128, 128]
dropout: 0.0
num_unfreeze_epochs: 10
loss_type: "MSE"
extractor_type: "FCAEModel"
lr: 0.0001
weight_decay: 0.00005
