_target_: src.datamodules.dnam_datamodule.DNAmDataModule

data_fn: "E:/YandexDisk/Work/dnamvae/data/datasets/unn/data.pkl"
cpgs_fn: "E:/YandexDisk/Work/dnamvae/data/annotation/cpgs.pkl"
outcome: "Age"
batch_size: 5
train_val_test_split: [130, 30, 24]
num_workers: 0
pin_memory: False
