_target_: src.datamodules.dnam_datamodule.DNAmDataModule

data_fn: "${data_dir}/combo/GSE40279_GSE87571_EPIC_GSE55763/vt_score_more_0.005_none/data_nn.pkl"
outcome: "age"
batch_size: 5
train_val_test_split: [0.8, 0.2, 0.0]
num_workers: 0
pin_memory: False
