_target_: src.datamodules.dnam_datamodule.DNAmDataModule

data_fn: "${data_dir}/GSE87571/data_nn.pkl"
outcome: "age"
batch_size: 5
train_val_test_split: [529, 100, 100]
num_workers: 0
pin_memory: False
